version: '3.9'
services:
  database:
    hostname: mongo-dbh
    container_name: daily-standup-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/db"
    networks:
      - network1
    restart: always

  backend:
    build: ./daily-standup-backend/
    container_name: daily-standup-backend
    depends_on:
        - database
    ports:
        - '8000:8000'
    networks:
      - network1
      - network2
    
  frontend:
    build: ./daily-standup-frontend/
    container_name: daily-standup-frontend
    depends_on:
        - backend
    ports:
        - '4001:3000'
    networks:
      - network2

  nginx:
    container_name: daily-standup-proxy
    build: ./daily-standup-frontend/nginx/
    ports:
      - "3050:80"
    restart: always
    depends_on:
        - frontend
    networks:
      - network2

volumes:
   mongodata:

networks:
   network1:
   network2:
